engine:
  fps:
    target: 60
    animation: 12
viewport:
  x: 0
  y: 0
  width: 1024
  height: 768
player:
  asset:
    path: "https://sparrow-assets.pages.dev/sparrow-comp.png"
  width: 128
  height: 128
  x: 128
  y: 100
map:
  width: 2048
  height: 1536
  bg: "https://sparrow-assets.pages.dev/map1-bg-full-comp.png"
  mg: "https://sparrow-assets.pages.dev/map1-mg-full-comp.png"
  fg: "https://sparrow-assets.pages.dev/map1-fg-full-comp.png"
  col: "https://sparrow-assets.pages.dev/map1-collision.png"
  collision:
    visible: true
  item:
    asset:
      one:
        width: 64
        height: 64
        path: "https://sparrow-assets.pages.dev/greenie-full.png"
      two:
        width: 64
        height: 64
        path: "https://sparrow-assets.pages.dev/finish-item.png"
    position:
      # noinspection SpringBootApplicationYaml
      0:
        x: 0
        y: 450
        type: "collectable"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      1:
        x: 797
        y: 450
        type: "finish"
        ref: "two"
  enemy:
    asset:
      one:
        width: 128
        height: 128
        path: "https://sparrow-assets.pages.dev/vacuum.png"
      two:
        width: 128
        height: 64
        path: "https://sparrow-assets.pages.dev/deebot-full.png"
    position:
      # noinspection SpringBootApplicationYaml
      0:
        x: 1600
        y: 450
        type: "blocker"
        ref: "one"
      # noinspection SpringBootApplicationYaml
      1:
        x: 1500
        y: 224
        type: "shooter"
        ref: "two"
      # noinspection SpringBootApplicationYaml
      2:
        x: 500
        y: 672
        type: "runner"
        ref: "two"
  directive:
    initial:
      text: "Collect all the greenies!"
      color: "black"
    finish:
      text: "Find the golden greenie!"
      color: "red"
    complete:
      text: "You won!"
      color: "blue"


particle:
  player:
    movement:
      # noinspection SpringBootApplicationYaml
      color:
        r: 230
        g: 234
        b: 218
        a: 255
    collision:
      # noinspection SpringBootApplicationYaml
      color:
        r: 255
        g: 255
        b: 255
        a: 255
  enemy:
    projectile:
      # noinspection SpringBootApplicationYaml
      color:
        r: 255
        g: 255
        b: 255
        a: 255
audio:
  player:
    jump: "https://sparrow-assets.pages.dev/jump-sound.wav"
    collision: "https://sparrow-assets.pages.dev/player-collision.wav"
  item:
    collect: "https://sparrow-assets.pages.dev/item-collect.wav"
  background: "https://sparrow-assets.pages.dev/level-1-music.wav"
  enemy:
    shoot: "https://sparrow-assets.pages.dev/shoot.wav"
